lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - "kafka.server:type=BrokerTopicMetrics,name=*"
  - "kafka.server:type=ReplicaManager,name=*"
  - "kafka.server:type=KafkaRequestHandlerPool,name=*"
  - "kafka.controller:type=KafkaController,name=*"
  - "kafka.network:type=RequestMetrics,name=*,request=*"
  - "java.lang:type=Memory"
  - "java.lang:type=GarbageCollector,*"
  - "java.lang:type=Threading"
  - "java.lang:type=Runtime"
  - "java.lang:type=OperatingSystem"