apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-config
  namespace: citystream
data:
  jmx-config.yaml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    whitelistObjectNames:
      - "kafka.server:type=BrokerTopicMetrics,name=*"
      - "kafka.server:type=ReplicaManager,name=*"
      - "kafka.server:type=KafkaRequestHandlerPool,name=*"
      - "kafka.controller:type=KafkaController,name=*"
      - "kafka.network:type=RequestMetrics,name=*,request=*"
      - "java.lang:type=Memory"
      - "java.lang:type=GarbageCollector,*"
      - "java.lang:type=Threading"
      - "java.lang:type=Runtime"
      - "java.lang:type=OperatingSystem"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: citystream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7071"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: kafka
        image: kafka-jmx:2.13-2.8.1
        imagePullPolicy: Never
        command: ["/bin/bash"]
        args:
          - -c
          - |
            # Start Kafka with JMX agent
            export KAFKA_OPTS="-javaagent:/opt/jmx_prometheus_javaagent.jar=7071:/opt/jmx-config.yaml"
            /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties \
              --override broker.id=1 \
              --override zookeeper.connect=zookeeper:2181 \
              --override listeners=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093 \
              --override advertised.listeners=INTERNAL://kafka:9092,EXTERNAL://localhost:9093 \
              --override listener.security.protocol.map=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
              --override inter.broker.listener.name=INTERNAL \
              --override auto.create.topics.enable=true \
              --override offsets.topic.replication.factor=1
        ports:
        - containerPort: 9092
          name: internal
        - containerPort: 9093
          name: external
        - containerPort: 7071
          name: metrics
        volumeMounts:
        - name: jmx-config
          mountPath: /opt/jmx-config.yaml
          subPath: jmx-config.yaml
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 45
          periodSeconds: 10
      volumes:
      - name: jmx-config
        configMap:
          name: kafka-jmx-config
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: citystream
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    targetPort: 9092
    name: internal
  - port: 9093
    targetPort: 9093
    name: external
  - port: 7071
    targetPort: 7071
    name: metrics