apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: citystream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: producer
        image: citystream-producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SERVER_PORT
          value: "8081"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 90
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: citystream
  labels:
    app: producer
spec:
  selector:
    app: producer
  ports:
  - port: 8081
    targetPort: 8081
    name: http