server:
  persistentVolume:
    enabled: false  # Disable for Minikube simplicity
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  enabled: false  # Not needed for now

pushgateway:
  enabled: false  # Not needed for now

nodeExporter:
  enabled: false  # Not needed for local Minikube

kubeStateMetrics:
  enabled: true  # Collects K8s resource metrics